from POM.module import HomeStay
class TestModule:
    def test_module(self,_driver):
        lp=HomeStay(_driver)
        lp.click_language1()
        lp.select_india()
        lp.select_india_click()
        lp.select_hindi_lan()
        lp.hindi_btn()
        lp.click_language3()
        lp.india_tamil_lan()
        lp.india_tamil_btn()
        lp.click_language4()
        lp.select_UAE()
        lp.select_uae_click()
        lp.uae_urdu_lan()
        lp.uae_urdu_btn()
        lp.click_language6()
        lp.select_usa()
        lp.select_usa_click()
        lp.usa_english_lan()
        lp.usa_english_btn()
        lp.click_language2()
        lp.select_india1()
        lp.select_india1_click()
        lp.india_english_lan()
        lp.india_english_btn()
        lp.Click_homestay()
        lp.select_place()
        lp.click_selected_place()
        lp.checkin_date()
        lp.checkout_date()
        lp.no_of_person()
        lp.click_onappyly()
        lp.click_onsearch()
        lp.select_hotel()